#%RAML 1.0 ResourceType

description: A list of <<itemsName>>
get:
  description: Get a list of <<itemsName>>
  queryParameters:
    page?:
      description: Specify the page that you want to retrieve
      type: integer
      minimum: 1
  responses:
    200:
      description: Returns a list of <<itemsName>>
      body:
        type: object
        properties:
          count:
            description: Number of <<itemsName>> in results
            type: integer
          next:
            description: Link to the next results page
            type: string
            example: <<resourcePath>>/?page=3
          previous:
            description: Link to the previous results page
            type: string
            example: <<resourcePath>>/?page=1
          results: <<itemsName | !singularize | !uppercamelcase>>[]
post?:
  description: Create a new <<itemsName | !singularize>>
  body:
    type: <<itemsName | !singularize | !uppercamelcase>>
  responses:
    201:
      description: Created a new <<itemsName | !singularize>>
      body:
        type: <<itemsName | !singularize | !uppercamelcase>>
/{id}?:
  uriParameters:
    id:
      description: The id of <<itemsName | !singularize>>
      type: integer
  get?:
    description: Get a specific <<itemsName | !singularize>>
    responses:
      200:
        description: Returns a specific <<itemsName | !singularize>>
        body:
          type: <<itemsName | !singularize | !uppercamelcase>>
      404:
        description: Requested <<itemsName | !singularize>> not found
  put?:
    description: Updates a specific <<itemsName | !singularize>> data
    body:
      type: <<itemsName | !singularize | !uppercamelcase>>
    responses:
      200:
        description: Updates a specific <<itemsName | !singularize>> data
        body:
          type: <<itemsName | !singularize | !uppercamelcase>>
      404:
        description: Unable to update <<itemsName | !singularize>>
